catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
packages:
  - .
minimumReleaseAge: 20160
verifyDepsBeforeRun: install
blockExoticSubdeps: true
trustPolicy: no-downgrade
minimumReleaseAgeExclude:
  - "@marimo-team/*"
onlyBuiltDependencies: []
