// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
const spec_Word = {
  __proto__: null,
  NOT: 52,
  not: 52,
  Not: 52,
  AND: 76,
  and: 76,
  And: 76,
  OR: 78,
  or: 78,
  Or: 78,
};
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "&fOVQPOOOOQO'#Ca'#CaOeQPO'#CdO!zQPO'#CcOOQO'#Cm'#CmOOQO'#Cw'#CwOVQPO'#C`OOQO'#C`'#C`O#dQPO'#C_O#qQPO'#C^OVQPO'#CwQOQPOOOOQO'#Ce'#CeO#|QPO,58}O$dQPO,58}OOQO,58z,58zOOQO'#Cn'#CnOOQO'#Cq'#CqOVQPO'#CqO$uQPO,58yOOQO'#Co'#CoOVQPO'#CrO%SQPO,58xO%_QPO,59cOOQO'#Cf'#CfOOQO'#Ck'#CkO$dQPO'#CkO$dQPO1G.iOOQO1G.i1G.iOOQO,59],59]OOQO-E6o-E6oOOQO,59^,59^OOQO-E6p-E6pOOQO1G.}1G.}O%dQPO'#ClO%lQPO,59VOOQO7+$T7+$TO$dQPO'#CpO%qQPO,59WOOQO1G.q1G.qOOQO,59[,59[OOQO-E6n-E6n",
  stateData:
    "&P~OiOS~OUQOZSOjPOlYO~OUaXZaXgaXjaXlaXnWXoWXpWXqWXrWXsWXtWXvaXwaXmaX~Oo[Op[Oq[Or[Os[Ot[O~On]O~P!fOUQOZSOjPOlYOv`O~OgRXwRXmRX~P#ROwdOgQXmQX~OUhOZhO[hO]hO^hOljO~P!fOUhOZhO[hO]hO^hO~OgRawRamRa~P#ROwdOgQamQa~OmqO~OuuOm`X~OmwO~OuuOm`a~O][^U^~",
  goto: "$WlPPmsz!ZP!d!m!v!|PPPP#]#`!d#c#g#k#q#wPPPP#}QZORgYSXOYRoeUWOYeQ_USaWcRmb_UOUWYbce_TOUWYbce_ROUWYbceQ^RRk]Qi]Ql^QrjQtkRxuRl]RsjTbWcTeXfQvrRyvQcWRncQfXRpf_VOUWYbce",
  nodeNames:
    "⚠ Query OrExpr AndExpr NotExpr Not Word Filter FieldName ComparisonOp ScalarValue QuotedString Number Date RelativeDate FilterValue ValueList FreeText And Or",
  maxTerm: 39,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData:
    "*h~RnX^#Ppq#Pqr#trs$Pxy%myz%r|}%w}!O%|!Q![&e![!](t!^!_(y!_!`)W!`!a)]!c!})j#R#S)j#T#o)j#y#z#P$f$g#P%W-x)j7[<v)j#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#P&Gh&Il)j&Il&Kp)j*5S41d)j5FY;%`)j~#UYi~X^#Ppq#P#y#z#P$f$g#P#BY#BZ#P$IS$I_#P$I|$JO#P$JT$JU#P$KV$KW#P&FU&FV#P~#wP!_!`#z~$POq~~$SVOr$Prs$is#O$P#O#P$n#P;'S$P;'S;=`%g<%lO$P~$nOZ~~$qRO;'S$P;'S;=`$z;=`O$P~$}WOr$Prs$is#O$P#O#P$n#P;'S$P;'S;=`%g;=`<%l$P<%lO$P~%jP;=`<%l$P~%rOl~~%wOm~~%|Ou~~&PP!Q![&S~&VR!Q![&S!c!}&`#T#o&`~&eO^~~&jQ[~!O!P&p!Q!['O~&sP!Q![&v~&{P[~!Q![&v~'TQ[~!O!P&p!Q!['Z~'`Q[~!O!P&p!Q!['f~'kR[~}!O't!O!P&p!Q![(i~'wP!Q!['z~'}P!Q![(Q~(TP}!O(W~(ZP!Q![(^~(aP!Q![(d~(iO]~~(nQ[~!O!P&p!Q![(i~(yOn~~)OPt~!_!`)R~)WOp~~)]Or~~)bPs~!_!`)e~)jOo~~)o]U~wx)j}!O)j!O!P)j!Q![)j!c!})j#R#S)j#T#o)j%W-x)j7[<v)j&Gh&Il)j&Il&Kp)j*5S41d)j5FY;%`)j",
  tokenizers: [0],
  topRules: { Query: [0, 1] },
  specialized: [{ term: 6, get: (value) => spec_Word[value] || -1 }],
  tokenPrec: 225,
});
